name: Criar recursos AWS com Terraform
on:
  push:
    branches:
      - feature/actions

jobs:
  criar-recursos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar ambiente Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Inicializar Terraform
        working-directory: ./terraform/
        run: |
          source ./.export_template
          terraform init

      - name: Planejar recursos
        working-directory: ./terraform/
        run: |
          source ./.export_template
          terraform plan

      - name: Aplicar recursos
        working-directory: ./terraform/
        run: |
          source ./.export_template
          terraform apply -auto-approve
